# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c3f796e6d58f010b42928232396a3ba"
application_url = "https://manufacture-defining-nut-ana.trycloudflare.com"
embedded = true
name = "board-room-app"
handle = "board-room-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://manufacture-defining-nut-ana.trycloudflare.com/auth/callback",
  "https://manufacture-defining-nut-ana.trycloudflare.com/auth/shopify/callback",
  "https://manufacture-defining-nut-ana.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
